### ISSUE TITLE
Validation of given token failed. Possibly token expired.

### ISSUE THREAD

**Issue by theianjohnson** [AzimoLabs/apple-sign-in-php-sdk#6] opened 2021-01-09 23:39 UTC
Even trying with `php vendor/bin/phpunit vendor/azimolabs/apple-sign-in-php-sdk/tests/E2e/Auth/AppleJwtFetchingServiceTest.php` with a recent token I'm only getting `Validation of given token failed. Possibly token expired.`

```
$validationData = new ValidationData();
$validationData->setIssuer('https://appleid.apple.com');
$validationData->setAudience('com.********');

$appleJwtFetchingService = new Auth\Service\AppleJwtFetchingService(
    new Auth\Jwt\JwtParser(new Parser()),
    new Auth\Jwt\JwtVerifier(
        new Api\AppleApiClient(
            new GuzzleHttp\Client(
                [
                    'base_uri'        => 'https://appleid.apple.com',
                    'timeout'         => 5,
                    'connect_timeout' => 5,
                ]
            ),
            new Api\Factory\ResponseFactory()
        ),
        new RSA(),
        new Sha256()
    ),
    new Auth\Jwt\JwtValidator($validationData),
    new Auth\Factory\AppleJwtStructFactory()
);

$payload = $appleJwtFetchingService->getJwtPayload($request->id_token);
```

**Comment by hywak** [comment] 2021-01-10 10:54
Hey @theianjohnson,

Thanks for reporting the issue.

First what comes to my mind is that you set incorrect `audience`. For testing reasons please remove the third line in the code you provided `$validationData->setAudience('com.********');` and try or replace with correct one.

**Comment by theianjohnson** [comment] 2021-01-10 17:26
@hywak That was me just blanking the app I'm working on, I didn't actually put *** ;) I assume the audience should be the same as what I have as my bundle identifier? Ie `com.whatever.whatever` correct?

**Comment by hywak** [comment] 2021-01-10 17:55
@theianjohnson exactly. For testing reasons audience can be empty but it's strongly recommend to set it when releasing the app.

**Comment by theianjohnson** [comment] 2021-01-10 18:53
Ok I'll remove that for testing. I'm adding more debugging to try and figure out what's going on and is there any way to access the `$payload` that's returned? 

```
$payload = $appleJwtFetchingService->getJwtPayload($request->id_token);
$user_id = $payload->sub;

// Cannot access private property Azimo\Apple\Auth\Struct\JwtPayload::$sub {"exception":"[object] (Error(code: 0): Cannot access private property Azimo\\Apple\\Auth\\Struct\\JwtPayload::$sub
```

**Comment by hywak** [comment] 2021-01-11 12:57
All fields in `\Azimo\Apple\Auth\Struct\JwtPayload` class are private. You can fetch the sub value by using getter `\Azimo\Apple\Auth\Struct\JwtPayload::getSub`

**Comment by hywak** [comment] 2021-01-20 08:08
Hey @theianjohnson, Did you manage to solve your problem? Can I close that issue?

**Comment by hywak** [comment] 2021-02-01 11:42
No answer for more than 30 days. I suppose the problem is resolved. I'm closing the issue, in case of any further problems please open a new issue.

**Closed by hywak** 2021-02-01 11:42 UTC
