### ISSUE TITLE
Unsupported cryptographic algorithm passed `eXaunmL

### ISSUE THREAD

**Issue by AlexNovicov** [AzimoLabs/apple-sign-in-php-sdk#11] opened 2021-03-02 07:53 UTC
Hi!

Can you add new cryptographic algorithm eXaunmL?

**Comment by hywak** [comment] 2021-03-02 08:26
Hey @AlexNovicov ,

Thank you for raising the issue. Unfortunately, our iOS dev is on vacation right now and I can't generate a JWT token signed with `eXaunmL`. The issue is wired to me because the library actually parses support `eXaunmL`. Could you please send me your JWT via email? I'd try to reproduce that problem.

**Comment by AlexNovicov** [comment] 2021-03-02 09:18
So far, the logs show only one error. Perhaps this is an single case and we can wait for the you ios developer

**Comment by hywak** [comment] 2021-03-02 10:33
The only idea that comes to my mind is that Apple API didn't return expected auth keys. Do you have logs of response for Apple API call for that erroneous request?

**Comment by AlexNovicov** [comment] 2021-03-02 10:42
No, we only record exceptions

**Comment by hywak** [comment] 2021-03-04 12:35
It might be worth to add the logger to the guzzle client, it would be easier to debug the issue if it occurs in the future. Docs: https://docs.guzzlephp.org/en/stable/request-options.html#on-stats

```
//... rest of the code
new GuzzleHttp\Client(
    [
        'base_uri'        => 'https://appleid.apple.com',
        'timeout'         => 5,
        'connect_timeout' => 5,
        'on_stats'        => function (TransferStats $stats) {
            // You must check if a response was received before using the
            // response object.
            if ($stats->hasResponse()) {
                echo $stats->getResponse()->getStatusCode();
            } else {
                // Error data is handler specific. You will need to know what
                // type of error data your handler uses before using this
                // value.
                var_dump($stats->getHandlerErrorData());
            }
        },
    ]
),
//... rest of the code
```

**Comment by hywak** [comment] 2021-03-10 07:21
Closing the issue. If the error occurs again, open the new issue, please.

**Closed by hywak** 2021-03-10 07:21 UTC
